# Generated by Django 5.2.4 on 2025-08-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='doctor_notes',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
