# Generated by Django 5.2.4 on 2025-08-03 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_prescription'),
        ('patients', '0002_alter_patient_emergency_phone_alter_patient_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('result', models.TextField()),
                ('date_conducted', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='lab_results/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
